### ISSUE TITLE
Can't Build in FreeNAS Jail

### ISSUE THREAD

**Issue by russoj88** [tevador/RandomX#71]
RE: https://www.reddit.com/r/MoneroMining/comments/c0ysjp/share_your_randomx_benchmarks/ercp7zq?utm_source=share&utm_medium=web2x

I'm trying to build this on a FreeNAS box, in a jail.
The jail's version: `FreeBSD 11.2-STABLE`
```shell
root@randomX:~ # gcc --version
gcc (FreeBSD Ports Collection) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```shell
root@randomX:~/RandomX # git checkout v1.0.3
HEAD is now at e4b2270 Merge pull request #47 from tevador/pr-doc
root@randomX:~/RandomX # make
make: "/root/RandomX/makefile" line 16: Missing dependency operator
make: "/root/RandomX/makefile" line 19: Need an operator
make: "/root/RandomX/makefile" line 20: Missing dependency operator
make: "/root/RandomX/makefile" line 23: Need an operator
make: "/root/RandomX/makefile" line 162: warning: duplicate script for target "obj/%.o" ignored
make: "/root/RandomX/makefile" line 159: warning: using previous script for "obj/%.o" defined here
make: "/root/RandomX/makefile" line 165: warning: duplicate script for target "obj/%.o" ignored
make: "/root/RandomX/makefile" line 159: warning: using previous script for "obj/%.o" defined here
make: Fatal errors encountered -- cannot continue
make: stopped in /root/RandomX
```

I get slightly farther with gmake:
```shell
root@randomX:~/RandomX # gmake --version
GNU Make 4.2.1
Built for amd64-portbld-freebsd11.2
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

root@randomX:~/RandomX # gmake
c++ -std=c++11 -maes -O3 -flto -c src/virtual_memory.cpp -o obj/virtual_memory.o
src/virtual_memory.cpp:119:83: error: use of undeclared identifier 'MAP_HUGETLB'
        mem = mmap(nullptr, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE, -1, 0);
                                                                                         ^
src/virtual_memory.cpp:119:97: error: use of undeclared identifier 'MAP_POPULATE'
        mem = mmap(nullptr, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE, -1, 0);
                                                                                                       ^
2 errors generated.
gmake: *** [makefile:162: obj/virtual_memory.o] Error 1
```

**Comment by hyc** [comment]
Looks like FreeBSD's mmap() doesn't support huge pages directly.
https://www.unix.com/man-page/FreeBSD/2/mmap/

You might get the same effect using `MAP_ALIGNED_SUPER` instead of `MAP_HUGETLB`

**Comment by tevador** [comment]
I did this quick fix: d1210870a1f22e2c07426cd93da36fef3695f45b but I have no way to test it.

**Comment by russoj88** [comment]
@tevador I'll be in/out today, but I should be able to test often.  Unfortunately I don't know enough C++ to actually help, but here's what I got with that branch.
```shell
root@randomX:~/RandomX # gmake
c++ -std=c++11 -maes -O3 -flto -c src/aes_hash.cpp -o obj/aes_hash.o
cc -std=c99 -O3 -flto -c src/argon2_ref.c -o obj/argon2_ref.o
c++ -std=c++11 -maes -O3 -flto -c src/dataset.cpp -o obj/dataset.o
c++ -std=c++11 -maes -O3 -flto -c src/soft_aes.cpp -o obj/soft_aes.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_memory.cpp -o obj/virtual_memory.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted.cpp -o obj/vm_interpreted.o
c++ -std=c++11 -maes -O3 -flto -c src/allocator.cpp -o obj/allocator.o
c++ -std=c++11 -maes -O3 -flto -c src/assembly_generator_x86.cpp -o obj/assembly_generator_x86.o
c++ -std=c++11 -maes -O3 -flto -c src/instruction.cpp -o obj/instruction.o
c++ -std=c++11 -maes -O3 -flto -c src/randomx.cpp -o obj/randomx.o
c++ -std=c++11 -maes -O3 -flto -c src/superscalar.cpp -o obj/superscalar.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled.cpp -o obj/vm_compiled.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted_light.cpp -o obj/vm_interpreted_light.o
cc -std=c99 -O3 -flto -c src/argon2_core.c -o obj/argon2_core.o
c++ -std=c++11 -maes -O3 -flto -c src/blake2_generator.cpp -o obj/blake2_generator.o
c++ -std=c++11 -maes -O3 -flto -c src/instructions_portable.cpp -o obj/instructions_portable.o
src/instructions_portable.cpp:29:14: warning: pragma STDC FENV_ACCESS ON is not
      supported, ignoring pragma [-Wunknown-pragmas]
#pragma STDC FENV_ACCESS ON
             ^
1 warning generated.
cc -std=c99 -O3 -flto -c src/reciprocal.c -o obj/reciprocal.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_machine.cpp -o obj/virtual_machine.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled_light.cpp -o obj/vm_compiled_light.o
cc -std=c99 -O3 -flto -c src/blake2/blake2b.c -o obj/blake2b.o
c++ -x assembler-with-cpp -c src/jit_compiler_x86_static.S -o obj/jit_compiler_x86_static.o
c++ -std=c++11 -maes -O3 -flto -c src/jit_compiler_x86.cpp -o obj/jit_compiler_x86.o
mkdir bin
gcc-ar rcs bin/librandomx.a obj/aes_hash.o obj/argon2_ref.o obj/dataset.o obj/soft_aes.o obj/virtual_memory.o obj/vm_interpreted.o obj/allocator.o obj/assembly_generator_x86.o obj/instruction.o obj/randomx.o obj/superscalar.o obj/vm_compiled.o obj/vm_interpreted_light.o obj/argon2_core.o obj/blake2_generator.o obj/instructions_portable.o obj/reciprocal.o obj/virtual_machine.o obj/vm_compiled_light.o obj/blake2b.o obj/jit_compiler_x86_static.o obj/jit_compiler_x86.o
gmake: gcc-ar: Command not found
gmake: *** [makefile:51: bin/librandomx.a] Error 127
```
I'm not sure if FreeBSD has a `gcc-ar` package/port.  I didn't find it running a search.

**Comment by hyc** [comment]
You should not need gcc-specific ar for this. Plain old `ar` should work.

**Comment by tevador** [comment]
`gcc-ar rcs` is equivalent to (for example):

```
ar rcs --plugin=/usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so
```

The plugin is needed for link time optimizations. If you use just `ar`, it will complain about a missing plugin.

**Comment by russoj88** [comment]
Setting AR to `ar` did complain about the plugin:
```shell
root@randomX:~/RandomX # gmake
c++ -std=c++11 -maes -O3 -flto -c src/aes_hash.cpp -o obj/aes_hash.o
cc -std=c99 -O3 -flto -c src/argon2_ref.c -o obj/argon2_ref.o
c++ -std=c++11 -maes -O3 -flto -c src/dataset.cpp -o obj/dataset.o
c++ -std=c++11 -maes -O3 -flto -c src/soft_aes.cpp -o obj/soft_aes.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_memory.cpp -o obj/virtual_memory.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted.cpp -o obj/vm_interpreted.o
c++ -std=c++11 -maes -O3 -flto -c src/allocator.cpp -o obj/allocator.o
c++ -std=c++11 -maes -O3 -flto -c src/assembly_generator_x86.cpp -o obj/assembly_generator_x86.o
c++ -std=c++11 -maes -O3 -flto -c src/instruction.cpp -o obj/instruction.o
c++ -std=c++11 -maes -O3 -flto -c src/randomx.cpp -o obj/randomx.o
c++ -std=c++11 -maes -O3 -flto -c src/superscalar.cpp -o obj/superscalar.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled.cpp -o obj/vm_compiled.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted_light.cpp -o obj/vm_interpreted_light.o
cc -std=c99 -O3 -flto -c src/argon2_core.c -o obj/argon2_core.o
c++ -std=c++11 -maes -O3 -flto -c src/blake2_generator.cpp -o obj/blake2_generator.o
c++ -std=c++11 -maes -O3 -flto -c src/instructions_portable.cpp -o obj/instructions_portable.o
src/instructions_portable.cpp:29:14: warning: pragma STDC FENV_ACCESS ON is not supported, ignoring pragma [-Wunknown-pragmas]
#pragma STDC FENV_ACCESS ON
             ^
1 warning generated.
cc -std=c99 -O3 -flto -c src/reciprocal.c -o obj/reciprocal.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_machine.cpp -o obj/virtual_machine.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled_light.cpp -o obj/vm_compiled_light.o
cc -std=c99 -O3 -flto -c src/blake2/blake2b.c -o obj/blake2b.o
c++ -x assembler-with-cpp -c src/jit_compiler_x86_static.S -o obj/jit_compiler_x86_static.o
c++ -std=c++11 -maes -O3 -flto -c src/jit_compiler_x86.cpp -o obj/jit_compiler_x86.o
ar rcs bin/librandomx.a obj/aes_hash.o obj/argon2_ref.o obj/dataset.o obj/soft_aes.o obj/virtual_memory.o obj/vm_interpreted.o obj/allocator.o obj/assembly_generator_x86.o obj/instruction.o obj/randomx.o obj/superscalar.o obj/vm_compiled.o obj/vm_interpreted_light.o obj/argon2_core.o obj/blake2_generator.o obj/instructions_portable.o obj/reciprocal.o obj/virtual_machine.o obj/vm_compiled_light.o obj/blake2b.o obj/jit_compiler_x86_static.o obj/jit_compiler_x86.o
c++ -std=c++11 -maes -O3 -flto -pthread -c src/tests/benchmark.cpp -o obj/benchmark.o
c++ -lpthread -flto -pthread obj/benchmark.o bin/librandomx.a -o bin/benchmark
/usr/bin/ld: unrecognized option '-plugin'
/usr/bin/ld: use the --help option for usage information
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [makefile:60: bin/benchmark] Error 1
```

**Comment by tevador** [comment]
You can try
```
make clean
make nolto
```

This will try to build without link time optimizations, which could work work with just `ar`. However, there can be a slight impact on performance.

**Comment by russoj88** [comment]
That built it!
I'm getting 1120H/s on an E3-1230v2 using 4 threads.   The number is +/- 5 with largePages.

Is there some known work to get those optimizations back in?

**Comment by tevador** [comment]
> The number is +/- 5 with largePages.

It means that large pages are not working.

> Is there some known work to get those optimizations back in?

You have to find out how to pass the lto plugin to `ar`. I'm not even sure what your compiler is.

**Comment by russoj88** [comment]
Here's the compiler I'm using:
```shell
root@randomX:~ # gcc --version
gcc (FreeBSD Ports Collection) 8.3.0
```

**Comment by monerorus** [comment]
> Setting AR to ar did complain about the plugin
how to do this?

**Comment by russoj88** [comment]
@monerorus [In the makefile, on line 3](https://github.com/tevador/RandomX/blob/master/makefile#L3)

**Comment by monerorus** [comment]
@russoj88 thx, i'm already find it :)

**Comment by tevador** [comment]
Solved in #74.

**Comment by russoj88** [comment]
@tevador this still doesn't build.  The makefile still references gcc-ar.  After changing it to ar, I tried building the master branch and this was the result:
```shell
root@randomX:~/RandomX # gmake
c++ -std=c++11 -maes -O3 -flto -c src/aes_hash.cpp -o obj/aes_hash.o
cc -std=c99 -O3 -flto -c src/argon2_ref.c -o obj/argon2_ref.o
c++ -std=c++11 -maes -O3 -flto -c src/bytecode_machine.cpp -o obj/bytecode_machine.o
c++ -std=c++11 -maes -O3 -flto -c src/dataset.cpp -o obj/dataset.o
c++ -std=c++11 -maes -O3 -flto -c src/soft_aes.cpp -o obj/soft_aes.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_memory.cpp -o obj/virtual_memory.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted.cpp -o obj/vm_interpreted.o
c++ -std=c++11 -maes -O3 -flto -c src/allocator.cpp -o obj/allocator.o
c++ -std=c++11 -maes -O3 -flto -c src/assembly_generator_x86.cpp -o obj/assembly_generator_x86.o
c++ -std=c++11 -maes -O3 -flto -c src/instruction.cpp -o obj/instruction.o
c++ -std=c++11 -maes -O3 -flto -c src/randomx.cpp -o obj/randomx.o
c++ -std=c++11 -maes -O3 -flto -c src/superscalar.cpp -o obj/superscalar.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled.cpp -o obj/vm_compiled.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_interpreted_light.cpp -o obj/vm_interpreted_light.o
cc -std=c99 -O3 -flto -c src/argon2_core.c -o obj/argon2_core.o
c++ -std=c++11 -maes -O3 -flto -c src/blake2_generator.cpp -o obj/blake2_generator.o
c++ -std=c++11 -maes -O3 -flto -c src/instructions_portable.cpp -o obj/instructions_portable.o
cc -std=c99 -O3 -flto -c src/reciprocal.c -o obj/reciprocal.o
c++ -std=c++11 -maes -O3 -flto -c src/virtual_machine.cpp -o obj/virtual_machine.o
c++ -std=c++11 -maes -O3 -flto -c src/vm_compiled_light.cpp -o obj/vm_compiled_light.o
cc -std=c99 -O3 -flto -c src/blake2/blake2b.c -o obj/blake2b.o
c++ -x assembler-with-cpp -c src/jit_compiler_x86_static.S -o obj/jit_compiler_x86_static.o
c++ -std=c++11 -maes -O3 -flto -c src/jit_compiler_x86.cpp -o obj/jit_compiler_x86.o
ar rcs bin/librandomx.a obj/aes_hash.o obj/argon2_ref.o obj/bytecode_machine.o obj/dataset.o obj/soft_aes.o obj/virtual_memory.o obj/vm_interpreted.o obj/allocator.o obj/assembly_generator_x86.o obj/instruction.o obj/randomx.o obj/superscalar.o obj/vm_compiled.o obj/vm_interpreted_light.o obj/argon2_core.o obj/blake2_generator.o obj/instructions_portable.o obj/reciprocal.o obj/virtual_machine.o obj/vm_compiled_light.o obj/blake2b.o obj/jit_compiler_x86_static.o obj/jit_compiler_x86.o
c++ -std=c++11 -maes -O3 -flto -pthread -c src/tests/benchmark.cpp -o obj/benchmark.o
c++ -lpthread -flto -pthread obj/benchmark.o bin/librandomx.a -o bin/randomx-benchmark
/usr/bin/ld: unrecognized option '-plugin'
/usr/bin/ld: use the --help option for usage information
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [makefile:68: bin/randomx-benchmark] Error 1
```

**Comment by tevador** [comment]
We will be deprecating the makefile soon in favor of `cmake`.

For the time being, you can build it easily like this:
```
make clean
make nolto
```
